

version: '2'

services:
  
  jenkins-docker:
    image: docker:dind
    networks:
      jenkins:
        aliases: 
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - .:/home

  jenkins-tutorial:
    image: jenkinsci/blueocean
    networks: 
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - .:/home
    ports: 
      - "8080:8080"

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks: 
  jenkins:
    